### PR TITLE
Update meter_izar.cc

### PR DESCRIPTION
**Pull request by ldebomy**
Serial number starts at 2

### CODE REVIEW

**Comment by weetmuts** [comment]
Thank you! When I rerun the tests on old telegrams, this fix will change the old serial numbers from 059196 to 159196
Ie they left pad the values with 0 to 6 digits. Now when we actually extract the most significant decimal digit, the zero turns into a one. Is this consistent with your own meter?

This will be a potentially breaking change to anyone who depends on the serial_number so I will document this in the CHANGES file. But hopefully, it might be that not so many users depend on this field.

**Comment by weetmuts** [comment]
@don-vip @jacek27 Just checking that this change is ok?

**Comment by don-vip** [comment]
Let me check for the meters I have. What's your model @ldebomy? Can you please share a frame?

**Comment by don-vip** [comment]
@weetmuts it's ok! I didn't notice my mistake because my serial number starts with 0. Thank you @ldebomy!

**Comment by weetmuts** [comment]
Thanks @Idebomy !

**Pull request merged**
