### PR TITLE
Use fedora gcc options to compile on Ubuntu (Don't Merge)

### PR DESCRIPTION
**Pull request by dwrobel**
Signed-off-by: Damian Wrobel <dwrobel@ertelnet.rybnik.pl>

### CODE REVIEW

**Comment by dwrobel** [comment]
This should help you track down the https://github.com/weetmuts/wmbusmeters/issues/509 issue. Once I temporarily added those options used by Fedora then I started observing wmbusmeters crashing as follows on my fork:
```
Run make test
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
Building dw-rpkg_
Segmentation fault (core dumped)
wmbusmeters returned error code: 1
Segmentation fault (core dumped)
ERROR: Test C1 meters
wmbusmeters returned error code: 1
Segmentation fault (core dumped)
wmbusmeters returned error code: 1
Segmentation fault (core dumped)
ERROR: Test T1 meters
wmbusmeters returned error code: 1
Segmentation fault (core dumped)
wmbusmeters returned error code: 1
Segmentation fault (core dumped)
ERROR: Test S1 meters
wmbusmeters returned error code: 1
Segmentation fault (core dumped)
wmbusmeters returned error code: 1
Segmentation fault (core dumped)
ERROR: Test electricity meters with radio converter plugins
wmbusmeters returned error code: 1
Segmentation fault (core dumped)
```

**Comment by dwrobel** [comment]
If you could consider merging https://github.com/weetmuts/wmbusmeters/pull/553 then we should start observing CI failing nicely on this PR.

**Comment by weetmuts** [comment]
Thanks, I can reproduce the problem. The static initializers are messed up. Some ordering problem,
they use variables that are not yet initialized, perhaps. :-)

This will take a little time to fix,  is there a more narrow set of gcc options that reproduce the problem.
Now the build time is like, 10 times longer. :-)

**Comment by dwrobel** [comment]
> is there a more narrow set of gcc options that reproduce the problem.

Frankly, I didn't check. It was my first shot to check whether the issue is also reproducible on Ubuntu. If you're interested on minimal set of options you could probably use binary-search to find it quickly.

**Comment by weetmuts** [comment]
Thanks for the options! I have now pushed a fix!

**Pull request closed without merging**
