### PR TITLE
LSE heat-cost-allocator + cold-water-meter

### PR DESCRIPTION
**Pull request by gswdn**
added driver mapping for Landis Staefa electronic heat-cost-allocator + cold-water-meter

#391 added support for LSE warmwater; a similar device exists for cold water and same driver can be used (`X(LSE_07_17,  MANUFACTURER_LSE, 0x07,  0x18)`)
Sample telegram:
`(telegram) DLL L=2d C=44 (from meter SND_NR) M=3265 (LSE) A=12362945 VER=18 TYPE=07 (Water meter) (driver unknown!) DEV=rtlwmbus[00000001] RSSI=93 (telegram) TPL CI=7a ACC=8d STS=00 CFG=0000 () Received telegram from: 12362945 manufacturer: (LSE) Landis Staefa electronic (0x3265) type: Water meter (0x07) ver: 0x18 device: rtlwmbus[00000001] rssi: 93 dBm driver: unknown! telegram=||2D4465324529361218077A8D0000000C13560501004C1300000000426CFFFF02BB560000326CFFFF046D2909BC2B|+0 `

Added driver mapping for HCA labelled with "Kalo K1.5X" and "Qundis GmbH, Erfurt". Kalo seems to be some kind of service provider for operational cost accounting. Maybe, Qundis sells their devices white-labelled to them? Or is it a cooperation with Siemens? Or Siemens sells white-label devices?

Anyway, they transmit as follows:

`(telegram) DLL L=26 C=44 (from meter SND_NR) M=3265 (LSE) A=89186680 VER=35 TYPE=08 (Heat Cost Allocator) (driver unknown!) DEV=rtlwmbus[00000001] RSSI=99 (telegram) TPL CI=7a ACC=8c STS=00 CFG=0000 () Received telegram from: 89186680 manufacturer: (LSE) Landis Staefa electronic (0x3265) type: Heat Cost Allocator (0x08) ver: 0x35 device: rtlwmbus[00000001] rssi: 99 dBm driver: unknown! telegram=||264465328066188935087A8C0000000B6E2600004B6E000000426CFFFF326CFFFF046D0905BC2B|+0 `

Driver QCALORIC (`X(QCALORIC,  MANUFACTURER_LSE, 0x08,  0x35) \`) can be used. Also see #203

### CODE REVIEW

**Comment by gswdn** [comment]
ups ... closed this PR by accident as I deleted its originating branch. Thought, I don't need this anymore after the PR. Sorry. Now, restored things again :) I'm quite new to this github things.

**Comment by makuser** [comment]
> Added driver mapping for HCA labelled with "Kalo K1.5X" and "Qundis GmbH, Erfurt". Kalo seems to be some kind of service provider for operational cost accounting. Maybe, Qundis sells their devices white-labelled to them? Or is it a cooperation with Siemens? Or Siemens sells white-label devices?

Qundis makes them all. In the case of Siemens, they just rebrand the hardware and provide their own software (readout/config) and also have a modified firmware which is based on the original Qundis FW. This is not uncommon in the industry, I know from other German manufacturers like Engelmann and Sontex they offer the same service, albeit maybe not as advanced as the partnership between Qundis and Siemens.

**Comment by weetmuts** [comment]
I have noticed that for some telegrams the branding for the device actually transmitting it, is so confusing
that there is no point in trying to give the driver a name that correlates with the branding. The driver
lse_07_17 is such a driver. 

Of course, eventually we should be able to make more generic drivers, since content often is very similar between
meters of the same type (water, hca etc.) But alas there is often some bits for error states that have to be translated since the wmbus standard does not specify those.

There is a new function to find possible matching drivers for unknown telegrams.
Try for example:
wmbusmeters --analyze 2D4465324529361218077A8D0000000C13560501004C1300000000426CFFFF02BB560000326CFFFF046D2909BC2B

The logic for finding the best match is not perfect, it just counts the understood content bytes. I will make it better
by giving preferable treatment to the important content bytes, like total water volume for water meters etc.

**Comment by weetmuts** [comment]
Thanks for the pull request!

**Pull request merged**
