### PR TITLE
Docker update

### PR DESCRIPTION
**Pull request by BIBOLV**
Moving docker building from CircleCI to docker actions. Tested built images on amd64 and arm64. Adding also dependabot checks for used github action script updates.

### CODE REVIEW

**Comment by BIBOLV** [comment]
Also to enable dependabot, you need to go to Insights -> Dependency Graph -> Dependabot and enable it.

**Comment by weetmuts** [comment]
Many thanks!

**Comment by BIBOLV** [comment]
Also looks line you will need to remove hook for circleci, or it will show up in commit checks.

**Comment by weetmuts** [comment]
Fixed!

**Pull request merged**
