### PR TITLE
Build and lint HomeAssistant addon in GitHub workflow

### PR DESCRIPTION
**Pull request by jannickfahlbusch**
The included HomeAssistant addon should be linted on pull requests.

I've also included a workflow to build the addon in a Workflow as Home Assistant would otherwise build the image locally.

This PR could also help to implement the HA addon testing as described in #735.

### CODE REVIEW

**Comment by BIBOLV** [comment]
Tnx for PR but please check https://github.com/wmbusmeters/wmbusmeters-ha-addon and https://github.com/weetmuts/wmbusmeters/pull/867 - it includes image building process and now is being prepared. 
Could you elaborate on testing - how it works and what is being tested?

**Comment by jannickfahlbusch** [comment]
Thank you for the hint, didn't knew about the new addon repo.

I can submit the linting to that repo if you'd like.

> Could you elaborate on testing - how it works and what is being tested?
Currently there is nothing tested. 
I think the first step would be to have an image that can be used without frequent needs to build said image.

**Comment by BIBOLV** [comment]
Yes, please submit all new changes to new repo. Thanks!

**Comment by jannickfahlbusch** [comment]
Submitted the linting part in https://github.com/wmbusmeters/wmbusmeters-ha-addon/pull/2

**Pull request closed without merging**
