### PR TITLE
Fixes for generating systemd service file

### PR DESCRIPTION
**Pull request by dwrobel**
Fixes the following warnings:
  - Unknown key name 'StartLimitIntervalSec' in section 'Service', ignoring,
    (moved to unit section)
  - PIDFile= references path below legacy directory /var/run/,
    (moved from /var/run -> /run)
  - kill: cannot find process "2>"
    (disable bash variable expansion while generating service file and
     simplify reload command by using $MAINPID systemd variable)

Add documentation url (github, and wmbusmeters(1))

Signed-off-by: Damian Wrobel <dwrobel@ertelnet.rybnik.pl>

### CODE REVIEW

**Comment by weetmuts** [comment]
Thanks, but what happened to StopWhenUnneeded=true ?
Is it not needed any more?

**Comment by weetmuts** [comment]
How often will the rpm be packaged? I am not at release version 1.0 yet, even though
the software is pretty stable by now. 

Should I expect the rpm to be repackacked every time I make a tag, or should
I make special tags to signal that it is a good time to make a new rpm?

**Comment by dwrobel** [comment]
>Thanks, but what happened to StopWhenUnneeded=true ?
>Is it not needed any more?

If I run the service by systemctl start then after a while the service is being stopped without any user intervention - so that seems to be not very convenient option.

**Comment by dwrobel** [comment]
>Should I expect the rpm to be repackacked every time I make a tag,

I'll try to package a new version/tag hower first, the package has to pass the oficiall review process [here](https://bugzilla.redhat.com/show_bug.cgi?id=1809263).

**Comment by weetmuts** [comment]
Now, when I plug in a wmbus-dongle, it auto-starts. When I unplug the dongle the daemon stops.
That is the use case. If you can get that working without StopWhenUnneeded=true,
then we do not need that option. :-)

**Comment by weetmuts** [comment]
I suppose what you are seeing, is when you use a dongle that cannot be udev detected 
(because they use a generic usb serial vendor id) then you want to do systemctl start
and have it running (at boot) forever. With a reliance on a udev rule starting the daemon.

If you are experiencing that the daemon stops, then this is a bug and you should 
open an issue for it.

**Comment by dwrobel** [comment]
>I suppose what you are seeing, is when you use a dongle that cannot be udev detected

It's fully detectable but it's the case when the user don't have in the udev rule: `ENV{SYSTEMD_WANTS}=`. Basically, I don't see any reason why it that case executing from either command line or tsystemd timer e.g.: `systemctl status wmbusmeters@-dev-rtlsdr_0.service` shouldn't work.
Well, it actually starts but then it stops after a few seconds _(due to StopWhenUnneeded=true)_.

When I added to udev rule the following:
```
# RTL2832U OEM vid/pid, e.g. ezcap EzTV668 (E4000), Newsky TV28T (E4000/R820T) etc.
SUBSYSTEMS=="usb", ATTRS{idVendor}=="0bda", ATTRS{idProduct}=="2838", GROUP:="rtlsdr", MODE:="0660", ENV{ID_SOFTWARE_RADIO}="1", TAG+="systemd", ENV{SYSTEMD_WANTS}="wmbusmeters@-dev-rtlsdr_0.service"
```
Then this is the log showing the behaviour of inserting the dongle and removing it after 10 seconds:
```
Mar 04 17:23:32 dell systemd[1]: Starting "wmbusmeters service on /dev/rtlsdr_0"...
Mar 04 17:23:32 dell wmbusmetersd[764249]: (wmbusmeters) started /run/wmbusmeters/wmbusmeters--dev-rtlsdr_0.pid
Mar 04 17:23:32 dell systemd[1]: Started "wmbusmeters service on /dev/rtlsdr_0".
Mar 04 17:23:32 dell wmbusmetersd[764251]: (config) loading meter file /etc/wmbusmeters.d/sensus
Mar 04 17:23:32 dell wmbusmetersd[764251]: (config) name=sensus
Mar 04 17:23:32 dell wmbusmetersd[764251]: (config) type=iperl
Mar 04 17:23:32 dell wmbusmetersd[764251]: (config) id=00111979
Mar 04 17:23:32 dell wmbusmetersd[764251]: (config) key=<notprinted>
Mar 04 17:23:32 dell wmbusmetersd[764251]: (config) shell=/usr/bin/mosquitto_pub -h piwnica -t stat/sensus/dw -m "$METER_JSON"
Mar 04 17:23:32 dell wmbusmetersd[764251]: (config) use rtlwmbus instead of raw device /dev/rtlsdr_0
Mar 04 17:23:32 dell wmbusmetersd[764251]: (config) overriding device with "rtlwmbus"
Mar 04 17:23:32 dell wmbusmetersd[764251]: (wmbusmeters) version: 0.9.27
Mar 04 17:23:32 dell wmbusmetersd[764251]: (config) using device: rtlwmbus
Mar 04 17:23:32 dell wmbusmetersd[764251]: (config) number of meters: 1
Mar 04 17:23:32 dell wmbusmetersd[764251]: (detect) "rtlwmbus" ""
Mar 04 17:23:32 dell wmbusmetersd[764251]: (detect) driver: rtlwmbus
Mar 04 17:23:32 dell wmbusmetersd[764251]: (rtlwmbus) using command: /usr/bin/rtl_sdr -f 868.95M -s 1.6e6 - 2>/dev/null | /usr/bin/rtl_wmbus
Mar 04 17:23:32 dell wmbusmetersd[764251]: (bgshell) exec background "/bin/sh"
Mar 04 17:23:32 dell wmbusmetersd[764251]: (bgshell) arg "-c"
Mar 04 17:23:32 dell wmbusmetersd[764251]: (bgshell) arg "/usr/bin/rtl_sdr -f 868.95M -s 1.6e6 - 2>/dev/null | /usr/bin/rtl_wmbus"
Mar 04 17:23:32 dell wmbusmetersd[764251]: (serialcmd) opened /bin/sh
Mar 04 17:23:32 dell wmbusmetersd[764251]: (config) meter iperl link mode(s): t1
Mar 04 17:23:32 dell wmbusmetersd[764251]: (config) all possible link modes that the meters might transmit on: t1
Mar 04 17:23:32 dell wmbusmetersd[764251]: (config) listen link modes calculated to be: t1
Mar 04 17:23:32 dell wmbusmetersd[764251]: (wmbusmeters) configured "sensus" "iperl" "00111979" not-encrypted
Mar 04 17:23:32 dell wmbusmetersd[764251]: (config) listen to link modes: any
Mar 04 17:23:32 dell wmbusmetersd[764251]: (wmbusmeters) waiting for telegrams
Mar 04 17:23:32 dell wmbusmetersd[764251]: (serial) waiting for stop
Mar 04 17:23:42 dell wmbusmetersd[764251]: (bgshell) 764253 exited with return code 2
Mar 04 17:23:42 dell wmbusmetersd[764251]: (serial) closing non working fd=4
Mar 04 17:23:42 dell wmbusmetersd[764251]: (serial) no devices working
Mar 04 17:23:42 dell wmbusmetersd[764251]: (serial) stopping manager
Mar 04 17:23:42 dell wmbusmetersd[764251]: (serialcmd) closed /bin/sh
Mar 04 17:23:42 dell wmbusmetersd[764251]: (serial) event loop stopped!
Mar 04 17:23:42 dell wmbusmetersd[764251]: (serial) closing 0 devices
Mar 04 17:23:42 dell wmbusmetersd[764251]: (wmbusmeters) shutting down
Mar 04 17:23:42 dell wmbusmetersd[764251]: (serial) no devices working
Mar 04 17:23:42 dell wmbusmetersd[764251]: (serialcmd) closed /bin/sh
Mar 04 17:23:42 dell systemd[1]: wmbusmeters@-dev-rtlsdr_0.service: Succeeded.
Mar 04 17:23:42 dell systemd[1]: wmbusmeters@-dev-rtlsdr_0.service: Consumed 1.354s CPU time.
Mar 04 17:23:43 dell systemd[1]: wmbusmeters@-dev-rtlsdr_0.service: Scheduled restart job, restart counter is at 1.
Mar 04 17:23:43 dell systemd[1]: Stopped "wmbusmeters service on /dev/rtlsdr_0".
Mar 04 17:23:43 dell systemd[1]: wmbusmeters@-dev-rtlsdr_0.service: Consumed 1.354s CPU time.
Mar 04 17:23:43 dell systemd[1]: Starting "wmbusmeters service on /dev/rtlsdr_0"...
Mar 04 17:23:43 dell wmbusmetersd[764279]: (wmbusmeters) started /run/wmbusmeters/wmbusmeters--dev-rtlsdr_0.pid
Mar 04 17:23:43 dell wmbusmetersd[764280]: (config) loading meter file /etc/wmbusmeters.d/sensus
Mar 04 17:23:43 dell systemd[1]: Started "wmbusmeters service on /dev/rtlsdr_0".
Mar 04 17:23:43 dell wmbusmetersd[764280]: (config) name=sensus
Mar 04 17:23:43 dell wmbusmetersd[764280]: (config) type=iperl
Mar 04 17:23:43 dell wmbusmetersd[764280]: (config) id=00111979
Mar 04 17:23:43 dell wmbusmetersd[764280]: (config) key=<notprinted>
Mar 04 17:23:43 dell wmbusmetersd[764280]: (config) shell=/usr/bin/mosquitto_pub -h piwnica -t stat/sensus/dw -m "$METER_JSON"
Mar 04 17:23:43 dell wmbusmetersd[764280]: (config) use rtlwmbus instead of raw device /dev/rtlsdr_0
Mar 04 17:23:43 dell wmbusmetersd[764280]: (config) overriding device with "rtlwmbus"
Mar 04 17:23:43 dell wmbusmetersd[764280]: (wmbusmeters) version: 0.9.27
Mar 04 17:23:43 dell wmbusmetersd[764280]: (config) using device: rtlwmbus
Mar 04 17:23:43 dell wmbusmetersd[764280]: (config) number of meters: 1
Mar 04 17:23:43 dell wmbusmetersd[764280]: (detect) "rtlwmbus" ""
Mar 04 17:23:43 dell wmbusmetersd[764280]: (detect) driver: rtlwmbus
Mar 04 17:23:43 dell wmbusmetersd[764280]: (rtlwmbus) using command: /usr/bin/rtl_sdr -f 868.95M -s 1.6e6 - 2>/dev/null | /usr/bin/rtl_wmbus
Mar 04 17:23:43 dell wmbusmetersd[764280]: (bgshell) exec background "/bin/sh"
Mar 04 17:23:43 dell wmbusmetersd[764280]: (bgshell) arg "-c"
Mar 04 17:23:43 dell wmbusmetersd[764280]: (bgshell) arg "/usr/bin/rtl_sdr -f 868.95M -s 1.6e6 - 2>/dev/null | /usr/bin/rtl_wmbus"
Mar 04 17:23:43 dell wmbusmetersd[764280]: (serialcmd) opened /bin/sh
Mar 04 17:23:43 dell wmbusmetersd[764280]: (config) meter iperl link mode(s): t1
Mar 04 17:23:43 dell wmbusmetersd[764280]: (config) all possible link modes that the meters might transmit on: t1
Mar 04 17:23:43 dell wmbusmetersd[764280]: (config) listen link modes calculated to be: t1
Mar 04 17:23:43 dell wmbusmetersd[764280]: (wmbusmeters) configured "sensus" "iperl" "00111979" not-encrypted
Mar 04 17:23:43 dell wmbusmetersd[764280]: (config) listen to link modes: any
Mar 04 17:23:43 dell wmbusmetersd[764280]: (wmbusmeters) waiting for telegrams
Mar 04 17:23:43 dell wmbusmetersd[764280]: (serial) waiting for stop
Mar 04 17:23:43 dell wmbusmetersd[764280]: (bgshell) 764282 exited with return code 2
Mar 04 17:23:43 dell wmbusmetersd[764280]: (serial) closing non working fd=4
Mar 04 17:23:43 dell wmbusmetersd[764280]: (serial) no devices working
Mar 04 17:23:43 dell wmbusmetersd[764280]: (serial) stopping manager
Mar 04 17:23:43 dell wmbusmetersd[764280]: (serialcmd) closed /bin/sh
Mar 04 17:23:43 dell wmbusmetersd[764280]: (serial) event loop stopped!
Mar 04 17:23:43 dell wmbusmetersd[764280]: (serial) closing 0 devices
Mar 04 17:23:43 dell wmbusmetersd[764280]: (wmbusmeters) shutting down
Mar 04 17:23:43 dell wmbusmetersd[764280]: (serial) no devices working
Mar 04 17:23:43 dell wmbusmetersd[764280]: (serialcmd) closed /bin/sh
Mar 04 17:23:43 dell systemd[1]: wmbusmeters@-dev-rtlsdr_0.service: Succeeded.
Mar 04 17:23:44 dell systemd[1]: wmbusmeters@-dev-rtlsdr_0.service: Scheduled restart job, restart counter is at 2.
Mar 04 17:23:44 dell systemd[1]: Stopped "wmbusmeters service on /dev/rtlsdr_0".
Mar 04 17:23:44 dell systemd[1]: Starting "wmbusmeters service on /dev/rtlsdr_0"...
Mar 04 17:23:44 dell wmbusmetersd[764291]: (wmbusmeters) started /run/wmbusmeters/wmbusmeters--dev-rtlsdr_0.pid
Mar 04 17:23:44 dell wmbusmetersd[764292]: (config) loading meter file /etc/wmbusmeters.d/sensus
Mar 04 17:23:44 dell systemd[1]: Started "wmbusmeters service on /dev/rtlsdr_0".
Mar 04 17:23:44 dell wmbusmetersd[764292]: (config) name=sensus
Mar 04 17:23:44 dell wmbusmetersd[764292]: (config) type=iperl
Mar 04 17:23:44 dell wmbusmetersd[764292]: (config) id=00111979
Mar 04 17:23:44 dell wmbusmetersd[764292]: (config) key=<notprinted>
Mar 04 17:23:44 dell wmbusmetersd[764292]: (config) shell=/usr/bin/mosquitto_pub -h piwnica -t stat/sensus/dw -m "$METER_JSON"
Mar 04 17:23:44 dell wmbusmetersd[764292]: (config) use rtlwmbus instead of raw device /dev/rtlsdr_0
Mar 04 17:23:44 dell wmbusmetersd[764292]: (config) overriding device with "rtlwmbus"
Mar 04 17:23:44 dell wmbusmetersd[764292]: (wmbusmeters) version: 0.9.27
Mar 04 17:23:44 dell wmbusmetersd[764292]: (config) using device: rtlwmbus
Mar 04 17:23:44 dell wmbusmetersd[764292]: (config) number of meters: 1
Mar 04 17:23:44 dell wmbusmetersd[764292]: (detect) "rtlwmbus" ""
Mar 04 17:23:44 dell wmbusmetersd[764292]: (detect) driver: rtlwmbus
Mar 04 17:23:44 dell wmbusmetersd[764292]: (rtlwmbus) using command: /usr/bin/rtl_sdr -f 868.95M -s 1.6e6 - 2>/dev/null | /usr/bin/rtl_wmbus
Mar 04 17:23:44 dell wmbusmetersd[764292]: (bgshell) exec background "/bin/sh"
Mar 04 17:23:44 dell wmbusmetersd[764292]: (bgshell) arg "-c"
Mar 04 17:23:44 dell wmbusmetersd[764292]: (bgshell) arg "/usr/bin/rtl_sdr -f 868.95M -s 1.6e6 - 2>/dev/null | /usr/bin/rtl_wmbus"
Mar 04 17:23:44 dell wmbusmetersd[764292]: (serialcmd) opened /bin/sh
Mar 04 17:23:44 dell wmbusmetersd[764292]: (config) meter iperl link mode(s): t1
Mar 04 17:23:44 dell wmbusmetersd[764292]: (config) all possible link modes that the meters might transmit on: t1
Mar 04 17:23:44 dell wmbusmetersd[764292]: (config) listen link modes calculated to be: t1
Mar 04 17:23:44 dell wmbusmetersd[764292]: (wmbusmeters) configured "sensus" "iperl" "00111979" not-encrypted
Mar 04 17:23:44 dell wmbusmetersd[764292]: (config) listen to link modes: any
Mar 04 17:23:44 dell wmbusmetersd[764292]: (wmbusmeters) waiting for telegrams
Mar 04 17:23:44 dell wmbusmetersd[764292]: (serial) waiting for stop
Mar 04 17:23:44 dell wmbusmetersd[764292]: (bgshell) 764294 exited with return code 2
Mar 04 17:23:44 dell wmbusmetersd[764292]: (serial) closing non working fd=4
Mar 04 17:23:44 dell wmbusmetersd[764292]: (serial) no devices working
Mar 04 17:23:44 dell wmbusmetersd[764292]: (serial) stopping manager
Mar 04 17:23:44 dell wmbusmetersd[764292]: (serialcmd) closed /bin/sh
Mar 04 17:23:44 dell wmbusmetersd[764292]: (serial) event loop stopped!
Mar 04 17:23:44 dell wmbusmetersd[764292]: (serial) closing 0 devices
Mar 04 17:23:44 dell wmbusmetersd[764292]: (wmbusmeters) shutting down
Mar 04 17:23:44 dell wmbusmetersd[764292]: (serial) no devices working
Mar 04 17:23:44 dell wmbusmetersd[764292]: (serialcmd) closed /bin/sh
Mar 04 17:23:44 dell systemd[1]: wmbusmeters@-dev-rtlsdr_0.service: Succeeded.
Mar 04 17:23:46 dell systemd[1]: wmbusmeters@-dev-rtlsdr_0.service: Scheduled restart job, restart counter is at 3.
Mar 04 17:23:46 dell systemd[1]: Stopped "wmbusmeters service on /dev/rtlsdr_0".
Mar 04 17:23:46 dell systemd[1]: Starting "wmbusmeters service on /dev/rtlsdr_0"...
Mar 04 17:23:46 dell wmbusmetersd[764300]: (wmbusmeters) started /run/wmbusmeters/wmbusmeters--dev-rtlsdr_0.pid
Mar 04 17:23:46 dell wmbusmetersd[764301]: (config) loading meter file /etc/wmbusmeters.d/sensus
Mar 04 17:23:46 dell systemd[1]: Started "wmbusmeters service on /dev/rtlsdr_0".
Mar 04 17:23:46 dell wmbusmetersd[764301]: (config) name=sensus
Mar 04 17:23:46 dell wmbusmetersd[764301]: (config) type=iperl
Mar 04 17:23:46 dell wmbusmetersd[764301]: (config) id=00111979
Mar 04 17:23:46 dell wmbusmetersd[764301]: (config) key=<notprinted>
Mar 04 17:23:46 dell wmbusmetersd[764301]: (config) shell=/usr/bin/mosquitto_pub -h piwnica -t stat/sensus/dw -m "$METER_JSON"
Mar 04 17:23:46 dell wmbusmetersd[764301]: (config) use rtlwmbus instead of raw device /dev/rtlsdr_0
Mar 04 17:23:46 dell wmbusmetersd[764301]: (config) overriding device with "rtlwmbus"
Mar 04 17:23:46 dell wmbusmetersd[764301]: (wmbusmeters) version: 0.9.27
Mar 04 17:23:46 dell wmbusmetersd[764301]: (config) using device: rtlwmbus
Mar 04 17:23:46 dell wmbusmetersd[764301]: (config) number of meters: 1
Mar 04 17:23:46 dell wmbusmetersd[764301]: (detect) "rtlwmbus" ""
Mar 04 17:23:46 dell wmbusmetersd[764301]: (detect) driver: rtlwmbus
Mar 04 17:23:46 dell wmbusmetersd[764301]: (rtlwmbus) using command: /usr/bin/rtl_sdr -f 868.95M -s 1.6e6 - 2>/dev/null | /usr/bin/rtl_wmbus
Mar 04 17:23:46 dell wmbusmetersd[764301]: (bgshell) exec background "/bin/sh"
Mar 04 17:23:46 dell wmbusmetersd[764301]: (bgshell) arg "-c"
Mar 04 17:23:46 dell wmbusmetersd[764301]: (bgshell) arg "/usr/bin/rtl_sdr -f 868.95M -s 1.6e6 - 2>/dev/null | /usr/bin/rtl_wmbus"
Mar 04 17:23:46 dell wmbusmetersd[764301]: (serialcmd) opened /bin/sh
Mar 04 17:23:46 dell wmbusmetersd[764301]: (config) meter iperl link mode(s): t1
Mar 04 17:23:46 dell wmbusmetersd[764301]: (config) all possible link modes that the meters might transmit on: t1
Mar 04 17:23:46 dell wmbusmetersd[764301]: (config) listen link modes calculated to be: t1
Mar 04 17:23:46 dell wmbusmetersd[764301]: (wmbusmeters) configured "sensus" "iperl" "00111979" not-encrypted
Mar 04 17:23:46 dell wmbusmetersd[764301]: (config) listen to link modes: any
Mar 04 17:23:46 dell wmbusmetersd[764301]: (wmbusmeters) waiting for telegrams
Mar 04 17:23:46 dell wmbusmetersd[764301]: (serial) waiting for stop
Mar 04 17:23:46 dell wmbusmetersd[764301]: (bgshell) 764303 exited with return code 2
Mar 04 17:23:46 dell wmbusmetersd[764301]: (serial) closing non working fd=4
Mar 04 17:23:46 dell wmbusmetersd[764301]: (serial) no devices working
Mar 04 17:23:46 dell wmbusmetersd[764301]: (serial) stopping manager
Mar 04 17:23:46 dell wmbusmetersd[764301]: (serialcmd) closed /bin/sh
Mar 04 17:23:46 dell wmbusmetersd[764301]: (serial) event loop stopped!
Mar 04 17:23:46 dell wmbusmetersd[764301]: (serial) closing 0 devices
Mar 04 17:23:46 dell wmbusmetersd[764301]: (wmbusmeters) shutting down
Mar 04 17:23:46 dell wmbusmetersd[764301]: (serial) no devices working
Mar 04 17:23:46 dell wmbusmetersd[764301]: (serialcmd) closed /bin/sh
Mar 04 17:23:46 dell systemd[1]: wmbusmeters@-dev-rtlsdr_0.service: Succeeded.
Mar 04 17:23:47 dell systemd[1]: wmbusmeters@-dev-rtlsdr_0.service: Scheduled restart job, restart counter is at 4.
Mar 04 17:23:47 dell systemd[1]: Stopped "wmbusmeters service on /dev/rtlsdr_0".
Mar 04 17:23:47 dell systemd[1]: wmbusmeters@-dev-rtlsdr_0.service: Start request repeated too quickly.
Mar 04 17:23:47 dell systemd[1]: wmbusmeters@-dev-rtlsdr_0.service: Failed with result 'start-limit-hit'.
Mar 04 17:23:47 dell systemd[1]: Failed to start "wmbusmeters service on /dev/rtlsdr_0".
```
So, as you might observe the service stops after reaching `StartLimitBurst=3`.

**Comment by weetmuts** [comment]
I will merge this and do a couple of experiments to see if I can safely remove stopwhenunneeded.
Keep your fingers crossed. :-)

**Comment by weetmuts** [comment]
Sadly, stopwhenunneeded is very much needed when the daemon is started using udev rules.
Without it, the daemon is started and when the dongle is removed, the daemon detects this and
nicely exists. However systemd will restart the daemon several times with the non-existant
device. Each time wmbusmeters nicely says, no dongle found on the device path.
Eventually systemd gives up.

So, I added to the README that if you do not want to use udev, then you have
also have to remote stopwhenunneeded....

Can you create a separate issue for your use case that is failing?

**Comment by weetmuts** [comment]
So I re-added stopwhenunneeded to the master.

**Comment by dwrobel** [comment]
>However systemd will restart the daemon several times with the non-existant
device.

I also mentioned that in my previous log [here](https://github.com/weetmuts/wmbusmeters/pull/89#issuecomment-594651465). The reason seems to be `StartLimitBurst=3`. So I removed that and currently I'm using a very minimalistic and general purpose version of the wmbusters@.service packaged in the `rpm` package:

```
[Unit]
Description="wmbusmeters service on %I"
Documentation=https://github.com/weetmuts/wmbusmeters
Documentation=man:wmbusmeters(1)
After=network.target

[Service]
Type=forking
ExecStart=/usr/sbin/wmbusmetersd --device='%I' /run/wmbusmeters/wmbusmeters-%i.pid
PIDFile=/run/wmbusmeters/wmbusmeters-%i.pid

[Install]
WantedBy=multi-user.target
```
the same applies to `wmbusters.conf`:
```
loglevel=debug
device=auto
logtelegrams=true
format=json
```

It works fine with and without `udev` and sends all of the output to the `journald`. If users wants to change the configuration the recommended way is to use either `systemctl edit <file.service>` or `drop-in` directory where you can specify additional options.

In future, I think it might be better to use [BindsTo=](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#BindsTo=) instead of using `ENV{SYSTEMD_WANTS}=` to connect with `udev`, but currently it's not properly implemented in the systemd.

**Comment by weetmuts** [comment]
I suggest using loglevel=normal, since debug will generate tons of logging information.

I will test your service file... :-)

**Comment by weetmuts** [comment]
Do you install the udev rules with the rpm package?

**Comment by dwrobel** [comment]
No, I don't _(I mean `wmbusmeters`)_. The dependency chain for the `udev` rules in that case is as follows:
- wmbusmeters
  - rtl-wmbus
      - rtl-sdr (which has `udev` defined rules [here](https://github.com/steve-m/librtlsdr/blob/master/rtl-sdr.rules)).

In other words installing `wmbusmeters` on `Fedora` will install appropriate `udev` rules indirectly _(provided by `rtl-sdr` package)_. I'm not sure how this looks like on the Debian/Ubuntu.

**Comment by weetmuts** [comment]
But wmbusmeters supports other wmbus specific dongles. Those are not provided for using rtl-sdr, so your rpm will not work with those dongles, right?

**Comment by dwrobel** [comment]
>your rpm will not work with those dongles, right?

They're mostly provided by a different packages already:

- 10c4:ea60 - provided by ModemManager,
- 0403:6001 - provided by libftdi,
- 0bda:2838 - provided by rtl-sdr,
- 2047:0863 - currently not provided.

So, there is only one single device currently not handled. But, anyway I would prefer not to package udev rules from wmbumeters because they automatically associates particular device with systemd service file - effectively starting this service upon device insertion which might be not what the user wanted to do by default _(they may simply want to use the device for a different purpose)_.

**Comment by weetmuts** [comment]
Ok, I created a new issue, please take a look here: https://github.com/weetmuts/wmbusmeters/issues/94

**Pull request merged**
