### PR TITLE
Add build rules for Debian package

### PR DESCRIPTION
**Pull request by petterreinholdtsen**
This is a draft. The build and runtime dependencies need more work, as well as the d/copyright and d/rules file. The 'make distclean' rule is incomplete and I worked around it in d/rules.

### CODE REVIEW

**Comment by petterreinholdtsen** [comment]
See also https://github.com/xaelsouth/rtl-wmbus/pull/36 for a dependency for this package.

Note, the d/copyright file was generated using ```deb/collect_copyrights.sh``` instead of ```debmake -cc```.  Both parses the source files to figure out their copyright licensing, but uses different heuristics. Several files are missing such information, making it harder than necessary to figure out the copyright information. It would be easier to keep the summary information up to date if all relevant files had licensing information at the top of the file.

**Comment by weetmuts** [comment]
Thanks! wmbusmeters does not strictly depend on rtl_wmbus, neither for building nor for runtime. (There are several other dongles that can be used for receiving radio telegrams.) But wmbusmeters is commonly used with rtl_wmbus.

**Comment by petterreinholdtsen** [comment]
[Fredrik Öhrström]
> Thanks! wmbusmeters does not strictly depend on rtl_wmbus, neither for
> building nor for runtime. (There are several other dongles that can be
> used for receiving radio telegrams.) But wmbusmeters is commonly used
> with rtl_wmbus.

Well, s/dependency/relationship/, use either Depends, Recommends or
Suggests at your leasure. :)

> Can we update the Makefile do build the correct deb package? The
> current code was walking in the wrong direction for creating a proper
> source package.

Just replace it all with a call to 'debuild'?
-- 
Happy hacking
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
I rewrote the debian build system to get 'make deb' working and by
staying away from debian/ by reusing the deb/ directory.  This make
third party packaging with separate debian/ setup easier.

-- 
Vennlig hilsen
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
This could be a start for fixing #460, ie getting the package into the Debian archive.

**Comment by weetmuts** [comment]
Yep! Many many thanks! Merged it so that I can start testing!

**Pull request merged**
