### PR TITLE
Improved multical403 support + M3/H <> L/H conversion

### PR DESCRIPTION
**Pull request by dddevvv**
See discusion PR #147

### CODE REVIEW

**Comment by weetmuts** [comment]
Thanks! But can you revert the change to the dockerfile?

**Comment by dddevvv** [comment]
> Thanks! But can you revert the change to the dockerfile?

Sorry, I assumed it would not end up in the PR, but of course it is automatically updated.

**Comment by weetmuts** [comment]
Great!

**Comment by weetmuts** [comment]
Do you have a telegram where these new codes are used? I would like to add an anonymized version of that telegram to the regression tests.

**Comment by dddevvv** [comment]
> Do you have a telegram where these new codes are used? I would like to add an anonymized version of that telegram to the regression tests.

Yes - see discussion in PR #147.
```
telegram=|42442D2C34232571340C8D20F9845B8021F14478|040FFA18000004FF07F173000004FF08D736000004140CA80000043B0000000002598014025D7F0C04FF2200000000|+357
```

**Pull request merged**
