### PR TITLE
Home Assistant add-on proposal

### PR DESCRIPTION
**Pull request by to-masz**
Add-ons in Home Assistant are a really easy way to integrate even complex libraries or programmes. See how easy it is to setup wmbusmeters with the add-on. It also leverages the HA MQTT broker.

out

Then quick integration in Home Assistant ...

And you can monitor the utility meter readings ...

---

### Things to note
* it does not use official docker images (there is a problem with `architecture` attribute of the images manifests)
* it does not use prebuilt add-on images (add-on image is compiled on the user device) - not a big problem, but can be improved in the future (e.g. CI build to include it)
* it was tested only with CUL dongle
* I have no idea how other USB dongles/devices can impact the `/dev/ttyUSB0` device path that is exposed to the add-on

### CODE REVIEW

**Comment by weetmuts** [comment]
Great work! It makes a lot of sense to have a supported official HASS add-on for wmbusmeters.
When the add-on is working I suppose we can update this documentation as well.
https://weetmuts.github.io/wmbusmeterswiki/HASS.html
 
Are these docker images separate from the current docker images? Should/can we have a single docker image?
@BIBOLV what do you think?

Are you @to-masz the person to contact for maintaining the wmbusmeters add-on when it is distributed through the official HASS add-ons?

If this docker image is built separately, then who is responsible for getting the image/setup into HASS?
Should we have the current CI for wmbusmeters build these docker images as well and push them to HASS,
or ping HASS to pull the built images?

**Comment by to-masz** [comment]
That dockerfile is completely independent from the current ones (still the main part is copy&paste). There is one thing to fix with the current images to make it possible to use them: `docker inspect weetmuts/wmbusmeters:release-1.4.0-arm64v8 | grep Arch ` gives `        "Architecture": "amd64",` which caused some problems with using them in add-on.

Once it is fixed I would use official images as a base. But there will be still a need for small integration with parsing the add-on configuration and translating it into wmbusmeters configuration files. 

I have spotted one thing that could be improved with dockerfile. Instead of `git clone` we should download the tarred release from https://github.com/weetmuts/wmbusmeters/releases. Otherwise the `RUN git clone ...` stays the same if you build locally and the output is taken from cache layer. 

---

I am ok with supporting the add-on, however as you probably experienced - many of the challenges are related with dongles (I have only CUL) and debugging the radio module telegrams (I would need your suggestions on what debugging mode should do) 😉 

Also the add-on won't probably land into the official add-ons repo. From https://github.com/hassio-addons/repository#adding-a-new-add-on:
> Adding a new add-on
> We are currently not accepting third party add-ons to this repository.

Therefore it works like that:
1. You add this repository to HomeAssistant Supervisor as add-ons repository on your own. 
2. Supervisor verifies if `repository.json` exists in the repository root
3. Supervisor scans all the folders and checks if `config.json` exists. If it does and is valid - it allows to install it. Also it does that check periodically to show new add-ons or updates to the existing ones (based on `version` attribute in `config.json`).
4. Then you can install the add-on
    - If there is `image` attribute in `config.json` it will pull the given docker image and use it. 
    - If there is not, it does docker build using the Dockerfile (it takes a while - I cut those 5 mins (?) from the gif 😅 ). 

Current CI could build the images. There is a dedicated build script that does some additional (and required for hassio) setps: https://github.com/home-assistant/builder. Please note, it is also available as Github action and you have probably 2000 mins of free computing power / a month in Github actions .

**Comment by BIBOLV** [comment]
Looks nice! I`m running all my HA instances in docker so doing all my integration manually and have no experience with add-ons, but I can build test instance and play around if help is needed, but looks like @to-masz have it covered. Though if help is needed, please let me know, I`ll pitch in. Also with docker or other stuff.
Regarding dongles and testing - all I`m using is one standard and one RTL-SDR. Standard dongles are working basically same way so IMO CUL is fine, RTL-SDR is bit different so to make proper tests it is needed. It is not that expensive, so you can buy one for testing and if you are tinkerer it might come handy in other projects. If not - let me know, I`ll send you one for this project.

**Comment by to-masz** [comment]
I will take a look at this MR again in the evening. There are few things I would like to improve ... and we will be ready to merge. 

- [ ] Using official image as a base
- [ ] Replace `git clone` in official image with versioned release download
- [ ] Optionally - replace multiple docker images with one and build arg

**Comment by andriej** [comment]
Which repo to add latest add-on on amd64 arch?

**Comment by to-masz** [comment]
@andriej are you able to tell me what is the device path in your HA OS? right now the add-on has configured `"devices": ["/dev/ttyUSB0"],` so supervisor maps only `/dev/ttyUSB0` into the add-on docker. 

@BIBOLV I saw your readme for official docker images. Should we rather run the add-on in privileged mode?

**Comment by andriej** [comment]
@to-masz I had an issue with that yesterday, as r820t sticks doesn't put up any /dev/ttyUSB* or ttyAMA etc. 
They just persist in /dev/usb/bus* and i.e. rtl_sdr or rtl_test just knows that they are present.

What's move difficult in my setup, I wanted to do it using USBoverIP, so even more possibiliteis to test for me.
Right now although I didn't manage to find any dev path that will be suitable.

All instructions regarding running rtl_sdr in docker put's up the priviliged mode with access to /dev/usb/bus, but I don't know if it's helpful info.

**Comment by BIBOLV** [comment]
@to-masz yes, to work with RTLSDR privileged mode is needed and /dev/* or some more specific paths exposed to HA. I opened ticket long time ago with rtlsdr about this, but there have not been any reaction so far.

**Comment by andriej** [comment]
Just to clarify - rtl_sdr and other rtl_*'s doesn't need path for specific device (/dev/tty*), probably handling /dev/bus/usb/* on their own.
They even work flawlessly with usboverip.

**Comment by BIBOLV** [comment]
Correct, just /dev/* covers both /dev/tty and /dev/bus/usb/*, so with one rule both rtlsdr and simple dongles.

**Comment by to-masz** [comment]
I have failed with using official docker image. I would like to keep using bashio (https://github.com/hassio-addons/bashio) - it allows to leverage mqtt broker without any effort. Any ideas how to combine those two images into one?

I enabled some additional options to map raw usb access and uart devices. @andriej can you check if that is enough?
More options here: https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config

**Comment by andriej** [comment]
@to-masz can test, sure - just please put it out into some repo so I can add it to HA

**Comment by andriej** [comment]
Managed to fork repo and merge changes.
Now in portainer's console I can see rtl_test running well (R820T directly connected to machine)
image

Now gonna find what options to use to receive apator's meter

**Comment by andriej** [comment]
With device=rtlwmbus:868.9M wasn't able to catch any frame yet, not sure if it works or may be it's lack of gain steering

**Comment by andriej** [comment]
Okay, after so many workarounds I got it working.
image

What doesn't work:
- [ ] logfile - it's empty, can't see log in add-on until I provide custom path ('/tmp/test' on screenshot
- [ ] MQTT - didn't manage to find a way to pass those MQTT variables (and I have quite strict ACL), so I put up custom .sh file based on the one from add-on and hardcoded `host`, `username` and `password` with credentials accessing `util/` topic.

What does work:
- I have the readings on MQTT! ;-)
- I have the readings from R820T stick connected to ethernet host via USBIP

I'll be happy to help further develop this add-on, as there's no easier way right now.
If there are concerns regarding proper implementation, maybe it's worth reaching out Frenck as he is responsible for community add-ons repo and also helping in that area.

**Comment by andriej** [comment]
Finding after night: only one declared meter out of two it's actually reporting to MQTT. I'm not sure if they are declared properly, please check screen, but it seems only the last declared is reported/analysed - garden water for me.

**Comment by andriej** [comment]
There was an issue ith meter_no calculation, quick fix:
image

**Comment by to-masz** [comment]
@andriej wow ... that was a nice debug. I have applied your fix - thanks

1. You can use now https://github.com/to-masz/wmbusmeters as a repo source (it points to MR's ha-addon branch in my fork)
2. Do you have external MQTT broker? Should we add an option to use a custom broker? It would be pretty easy ... and then we can fallback to the one internal of HA.
3. I have no idea why the log of add-on is empty in supervisor's add-on page. Can you check the supervisor logs (it is in the system tab of supervisor)?

**Comment by andriej** [comment]
I have MQTT broker provided by Mosquitto HA add-on (standard one), but with ACL activated and no anonymous login.
So it's not 'custom', but I neither got it working on first tries.

I might try one more time from your repo with fixes (as RTL-SDR is now working and both meters show up) to see if add-on manage to use ingress-mqtt

What worries me is the log of add-on being empty - I have checked Supervisor logs (none info there) and system logs (Debian 11 /var/log).
Even in portainer:
image

Maybe the fillter info will be some kind of hint?

**Comment by andriej** [comment]
Looking at:
https://github.com/to-masz/wmbusmeters/blob/ha-addon/ha-addon/Dockerfile
and 
https://github.com/hassio-addons/addon-wireguard/blob/main/wireguard/Dockerfile

I see that there may be some fields to look at (including base image?) as those are the best-class supported add-ons and have cooperation with supervisor implemented properly.
I'm not that good with dockers, so don't have ideas at the moment.

**Comment by andriej** [comment]
I have successfully tested ur repo with 'ingress MQTT' (so addon had credentials on its own).
Last thing that doesn't work is the log, which is still missing and while figgling with it I have successfully froze my whole machine 2 times (lost all connectivity while add-on restart).
Will dig into logs later.

**Comment by to-masz** [comment]
I have no Portainer, but simple `docker logs` works. Also I see the logs in the add-on logs tab in my instance.
Do you see logs in other addons successfully?

**Comment by andriej** [comment]
Yes, all other add-ons are ok.
Checked with docker logs directly, empty from wmbusmeters while all others visible as on WWW.

**Comment by andriej** [comment]
In supervisor logs, there's an warning thrown (while add-on works):
```
21-08-25 16:30:17 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/6a18d594/.circleci/config.yml: Invalid Add-on config!. Got ordereddict([('version', 2), ('jobs', ordereddict([('amd64', ordereddict([('machine', ordereddict([('enabled', True)])), ('steps', ['checkout', ordereddict([('run', ordereddict([('command', 'if [[ ! $CIRCLE_BRANCH ]]\nthen\n  DOCKER_TAG=release-$CIRCLE_TAG\nelse\n  DOCKER_TAG=latest\nfi\nsudo docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASS\nsudo docker build --pull -t $DOCKERHUB_REPO:$DOCKER_TAG-amd64 -f docker/Dockerfile .\nsudo docker push $DOCKERHUB_REPO:$DOCKER_TAG-amd6...
21-08-25 16:30:18 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/6a18d594/.circleci/config.yml: Invalid Add-on config!. Got ordereddict([('version', 2), ('jobs', ordereddict([('amd64', ordereddict([('machine', ordereddict([('enabled', True)])), ('steps', ['checkout', ordereddict([('run', ordereddict([('command', 'if [[ ! $CIRCLE_BRANCH ]]\nthen\n  DOCKER_TAG=release-$CIRCLE_TAG\nelse\n  DOCKER_TAG=latest\nfi\nsudo docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASS\nsudo docker build --pull -t $DOCKERHUB_REPO:$DOCKER_TAG-amd64 -f docker/Dockerfile .\nsudo docker push $DOCKERHUB_REPO:$DOCKER_TAG-amd6...
```

It's while refreshing add-ons list:
21-08-25 16:30:15 INFO (MainThread) [supervisor.store.git] Update add-on [...]

**Comment by weetmuts** [comment]
@to-masz Thanks! I have merged it! The documentation looks good. But I will actually try out the add-on myself. I will let you know!

**Comment by andriej** [comment]
There still are those messags in (main) Supervisor logs:
```
21-08-28 19:18:08 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/cada3e3b/.circleci/config.yml: Invalid Add-on config!. Got ordereddict([('version', 2), ('jobs', ordereddict([('amd64', ordereddict([('machine', ordereddict([('enabled', True)])), ('steps', ['checkout', ordereddict([('run', ordereddict([('command', 'if [[ ! $CIRCLE_BRANCH ]]\nthen\n  DOCKER_TAG=release-$CIRCLE_TAG\nelse\n  DOCKER_TAG=latest\nfi\nsudo docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASS\nsudo docker build --pull -t $DOCKERHUB_REPO:$DOCKER_TAG-amd64 -f docker/Dockerfile .\nsudo docker push $DOCKERHUB_REPO:$DOCKER_TAG-amd6...
21-08-28 19:18:08 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/cada3e3b/.circleci/config.yml: Invalid Add-on config!. Got ordereddict([('version', 2), ('jobs', ordereddict([('amd64', ordereddict([('machine', ordereddict([('enabled', True)])), ('steps', ['checkout', ordereddict([('run', ordereddict([('command', 'if [[ ! $CIRCLE_BRANCH ]]\nthen\n  DOCKER_TAG=release-$CIRCLE_TAG\nelse\n  DOCKER_TAG=latest\nfi\nsudo docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASS\nsudo docker build --pull -t $DOCKERHUB_REPO:$DOCKER_TAG-amd64 -f docker/Dockerfile .\nsudo docker push $DOCKERHUB_REPO:$DOCKER_TAG-amd6...
```
while everything works.

**Comment by andriej** [comment]
@to-masz I got report that there are issues when there's space in payload and there's easy way to fix that:
`$METER_NAME $METER_JSON` should be changed to: `$METER_NAME "$METER_JSON"`

**Comment by to-masz** [comment]
@andriej as it is on the master now - feel free to open Pull request to fix default configuration (you will find it in config.json)

**Comment by andriej** [comment]
@to-masz just FYI, issue with circleci was caused by Supervisor not ignoring files it should ignore. 
it will be fixed in it's next releases ;-)

**Pull request merged**
