### PR TITLE
Add support for HYDRUS 2.0

### PR DESCRIPTION
**Pull request by larsxschneider**
I got a HYDRUS 2.0 and added it - it looks like as if it is working 😄 . 

Is there anything else I need to do (tests, documentation,  ...)? If yes, then please point me to an exemplary Pull Request and then I will update this Pull Request accordingly.

### CODE REVIEW

**Comment by weetmuts** [comment]
Thanks for the offer to help! There is something that I do need help with, the conversion of old style drivers to the new format. The old drivers are called meter_xyz.cc and the new ones are driver_xyz.cc 
The new format is completely selfcontained, just drop such a cc file into the src dir and recompile and it will be available later. 

Here is an example of an old style driver:
https://github.com/weetmuts/wmbusmeters/blob/fc43958b769318bf41f144943d481845a1b0cf14/src/meter_ultrimis.cc

And here is the rewritten version:
https://github.com/weetmuts/wmbusmeters/blob/master/src/driver_ultrimis.cc

This particular driver still lacks some info on the bits in the status register. You simply
add `{ 0x01, "?" }, ` inside the lookup where there is a comment, to map that bit to that string.

Note that some driver_xyz.cc files are in an intermediate state where c++ class variables are still
used for storage. If you want you can clean up this to the latest format as well.

A very simple starter could be the meter_weh_07.cc to be converted into driver_weh_07.cc
You can find the example telegram in simulation/simulations_c1.txt 
494468509494949495377286868686A85CFE07A90030052F2F0413100000000F52FCF6A52A90A8D83CA8F7FEAE86990502323D0C70EFF49833C7C1696F75BCABC1E52E6305308D0F31FB

Just create the file driver_weh_07.cc and copy the driver_ultrimis.cc the change "ultrimis" to "weh_07_new"
But drop the addDetection line, which will conflict with the old driver.

Compile. Now you can compare the output from:
wmbusmeters --analyze=weh_07 4944.....31FB
with 
wmbusmeters --analyze=weh_07_new 4944......31FB

Modify the new driver until the json is identical.
Now remove the old meter_weh_07.cc file and remove weh_07 from meter_detection.h and meter.h
Restore the addDetection in the new driver and make sure the values are the same as the ones you removed from meter_detection.

Then change the test case at the end of the driver_weh_07.cc to use the right telegram.
Run "make test"

:-)

**Comment by larsxschneider** [comment]
Sorry, I am really busy with my day job currently... I'll get back to this PR as soon as I have more time. So it's not abandoned ... just delayed 😊

**Comment by weetmuts** [comment]
No worries! If you can collect just a single telegram from the new meter (--logtelegrams), that I can add to the test suite,  to prevent regressions. Also perhaps the old driver is working but there is more data available in your new meter.

**Comment by larsxschneider** [comment]
Here is the output of an analyzed package. I redacted my meter ID with `XXXXXXXX`. Please let me know if there is any other PII in there.
Does this help?

```
$ ./wmbusmeters --analyze "6344A511XXXXXXXX76078C00B2900F002C259F030E00ADA53F29BA01A3137A9F004107102F2F_0C1397640100426CBF2C4C13160400004C933C000000000B3B00000002FD743D1C0A66950184046D3B37DF258C0413135900000A5A050204FD1700000001"
Auto driver  : hydrus
Best driver  : hydrus(driver should be upgraded) 19/35
Using driver : hydrus(driver should be upgraded) 00/00
000   : 63 length (99 bytes)
001   : 44 dll-c (from meter SND_NR)
002   : a511 dll-mfct (DME)
004   : XXXXXXXX dll-id (XXXXXXXX)
008   : 76 dll-version
009   : 07 dll-type (Water meter)
010   : 8c ell-ci-field (ELL: Extended Link Layer I (2 Byte))
011   : 00 ell-cc (slow_resp)
012   : b2 ell-acc
013   : 90 afl-ci-field (AFL: Authentication and Fragmentation Sublayer)
014   : 0f afl-len (15)
015   : 002c afl-fc (0 MACInFragment MessCounterInFragment MessControlInFragment LastFragment)
017   : 25 afl-mcl (AES_CMAC_128_8 MessCounter)
018   : 9f030e00 afl-counter (918431)
022   : ADA53F29BA01A313 afl-mac 8 bytes
030   : 7a tpl-ci-field (EN 13757-3 Application Layer (short tplh))
031   : 9f tpl-acc-field
032   : 00 tpl-sts-field (OK)
033   : 4107 tpl-cfg 0741 (AES_CBC_NO_IV )
035   : 10 tpl-cfg-ext (KDFS=1)
036   : 2f2f already decrypted check bytes
038   : 0C dif (8 digit BCD Instantaneous value)
039   : 13 vif (Volume l)
040 C!: 97640100 total consumption (16.497000 m3)
044   : 42 dif (16 Bit Integer/Binary Instantaneous value storagenr=1)
045   : 6C vif (Date type G)
046 C!: BF2C at date (2021-12-31 00:00)
048   : 4C dif (8 digit BCD Instantaneous value storagenr=1)
049   : 13 vif (Volume l)
050 C!: 16040000 total consumption at date (0.416000 m3)
054   : 4C dif (8 digit BCD Instantaneous value storagenr=1)
055   : 93 vif (Volume l)
056   : 3C vife (backward flow)
057 C?: 00000000
061   : 0B dif (6 digit BCD Instantaneous value)
062   : 3B vif (Volume flow l/h)
063 C!: 000000 max flow (0.000000 m3/h)
066   : 02 dif (16 Bit Integer/Binary Instantaneous value)
067   : FD vif (Second extension FD of VIF-codes)
068   : 74 vife (Reserved)
069 C!: 3D1C battery life (7229 days 19.791923 years)
071   : 0A dif (4 digit BCD Instantaneous value)
072   : 66 vif (External temperature 10⁻¹ °C)
073 C!: 9501 external temperature (19.500000 °C)
075   : 84 dif (32 Bit Integer/Binary Instantaneous value)
076   : 04 dife (subunit=0 tariff=0 storagenr=8)
077   : 6D vif (Date and time type)
078 C?: 3B37DF25
082   : 8C dif (8 digit BCD Instantaneous value)
083   : 04 dife (subunit=0 tariff=0 storagenr=8)
084   : 13 vif (Volume l)
085 C?: 13590000
089   : 0A dif (4 digit BCD Instantaneous value)
090   : 5A vif (Flow temperature 10⁻¹ °C)
091 C!: 0502 flow temperature (20.500000 °C)
093   : 04 dif (32 Bit Integer/Binary Instantaneous value)
094   : FD vif (Second extension FD of VIF-codes)
095   : 17 vife (Error flags (binary))
096 C?: 00000001

{
    "media":"water",
    "meter":"hydrus",
    "name":"",
    "id":"XXXXXXXX",
    "total_m3":16.497,
    "total_tariff1_m3":0,
    "total_tariff2_m3":0,
    "max_flow_m3h":0,
    "flow_temperature_c":20.5,
    "external_temperature_c":19.5,
    "current_date":"",
    "total_at_date_m3":0.416,
    "total_tariff1_at_date_m3":0,
    "total_tariff2_at_date_m3":0,
    "at_date":"2021-12-31 00:00",
    "actuality_duration_s":0,
    "operating_time_h":0,
    "remaining_battery_life_y":19.791923,
    "status":"OK",
    "timestamp":"2022-06-20T17:28:14Z"
}
```

**Comment by weetmuts** [comment]
Yes it does! Many thanks! Now I can convert the hydrus driver and add the fields that your telegram has as well.

**Pull request merged**
