### PR TITLE
Add sensostar2

### PR DESCRIPTION
**Pull request by psxde**
Add Engelmann Sensostar2 to heat meters and recognize Engelmann FAW water meter radio module as waterstar beause it seems to be the same protocol

### CODE REVIEW

**Comment by weetmuts** [comment]
Very nice! Do you have a telegram that we can anonymize and put into simulations/simulation_t1.txt (or c1)
You can get one with --logtelegram and then just change the id (assuming the id is 12345678, its recorded
as 78563412 in the telegram hex text.

**Comment by psxde** [comment]
# Sensostar 2
telegram=|9E44C5147856341200047A7B0090052F2F|046D25248A2B04063D1F000001FD17000415265F00004406131F0000840106901E0000C40106841E0000840206841E0000C402067A1E0000840306541E0000C40306021E00008404069E1D0000C40406D71C0000840506F21B0000C40506681A00008406061E190000C40606EB1700008407061C170000C40706EE1600002F2F2F2F2F2F2F2F2F2F2F2F2F2F2F2F|+135

**Comment by weetmuts** [comment]
Thanks!

**Comment by weetmuts** [comment]
And  pushed the regression test!

**Pull request merged**
