### PR TITLE
Ie6500

### PR DESCRIPTION
**Pull request by rattinca**
Not sure where the empty file came from and how to get rid of the makefile.txt... But hopefully you can take just the parts you need?

### CODE REVIEW

**Comment by weetmuts** [comment]
Thank you! I took your code an rewrote it a bit to get it to fit better into wmbusmeters.
I renamed the meter driver to ei6500, since the meter name seems to be EI Electronics ei6500-oms.

It seems like the only value that indicates smoke detected is the smoke counter? 

There are still some states that are not properly decoded in the telegram. 
Can you continue the work and add them?

// What date is this?
(ei6500) 22: 82 dif (16 Bit Integer/Binary Instantaneous value)
(ei6500) 23: 20 dife (subunit=0 tariff=2 storagenr=0)
(ei6500) 24: 6C vif (Date type G)
(ei6500) 25: AB22

// And this?
(ei6500) 27: 42 dif (16 Bit Integer/Binary Instantaneous value storagenr=1)
(ei6500) 28: 6C vif (Date type G)
(ei6500) 29: 0101

// Extra status bits not decoded?
(ei6500) 2b: 84 dif (32 Bit Integer/Binary Instantaneous value)
(ei6500) 2c: 40 dife (subunit=1 tariff=0 storagenr=0)
(ei6500) 2d: FF vif (Vendor extension)
(ei6500) 2e: 2C vife (per litre)
(ei6500) 2f: 000F1100

**Comment by weetmuts** [comment]
I am closing this pull request. Please open a new one with additional decode code, or open an issue. Thanks!

**Comment by rattinca** [comment]
Yeah, thx, i noticed to late i named it wrong x-)
i will try and update your version with new information.

There is no boolean for smoke just the counter and the date gets updated.

While the prosess is running it keeps the variables from the last message, does it not?
So it should be possible to set it to smoke alarm when the counter goes up?

**Comment by ElKaPa** [comment]
> Thank you! I took your code an rewrote it a bit to get it to fit better into wmbusmeters.
> I renamed the meter driver to ei6500, since the meter name seems to be EI Electronics ei6500-oms.
> 
> It seems like the only value that indicates smoke detected is the smoke counter?
> 
> There are still some states that are not properly decoded in the telegram.
> Can you continue the work and add them?
> 
> // What date is this?
> (ei6500) 22: 82 dif (16 Bit Integer/Binary Instantaneous value)
> (ei6500) 23: 20 dife (subunit=0 tariff=2 storagenr=0)
> (ei6500) 24: 6C vif (Date type G)
> (ei6500) 25: AB22
> 
This is the commission date when the Ei6500 is installed for the first time


> // And this?
> (ei6500) 27: 42 dif (16 Bit Integer/Binary Instantaneous value storagenr=1)
> (ei6500) 28: 6C vif (Date type G)
> (ei6500) 29: 0101
> 

This is the date of the last sounder test (piezo check)
Usually at the 16th of every month at 3pm UTC

> // Extra status bits not decoded?
> (ei6500) 2b: 84 dif (32 Bit Integer/Binary Instantaneous value)
> (ei6500) 2c: 40 dife (subunit=1 tariff=0 storagenr=0)
> (ei6500) 2d: FF vif (Vendor extension)
> (ei6500) 2e: 2C vife (per litre)
> (ei6500) 2f: 000F1100

These are the smoke detector head status bytes

Bit 0-4 = Dust level 0= best 15= worst
Bit 5 = Sounder fault flag
Bit 6 = Head tamper flag true while removed from mounting plate
Bit 7 = EOL reached flag
Bit 8-11 = Battery voltage level 0-15 (level * 0.05V)+ 2.25V
Bit 12 = low battery fault flag
Bit 13 = alarm sensor fault flag
Bit 14 = obstacle detection fault flag
Bit 15 = EOL within 12 month flag
Bit 16 = obstacle detecting installation ok flag
Bit 17 = Environment has changed since last installation flag
Bit 18 = communication to head fault flag
Bit 19 = obstacle detecting not possible due to interference flag
Bit 20-22 = obstacle detection distance to object

0= installation not complete
1= no obstacle detected
2=45-60cm
3=37.5-52.5cm
4=32.5-47.5cm
5=27.5-40cm
6=20-32.5cm
7=0-25cm
Bit 24 = obstacle detected flag
Bit 25 = smoke detector fully covered flag

**Pull request closed without merging**
