### PR TITLE
Add support for Zenner Minomess water meter

### PR DESCRIPTION
**Pull request by trsqr**
Add initial support for Zenner Minomess C1 Mode water meter.

### CODE REVIEW

**Comment by trsqr** [comment]
This solves https://github.com/weetmuts/wmbusmeters/issues/384

**Comment by weetmuts** [comment]
Great work! Do you think you can add a test telegram to simulations/simulation_c1_meters.txt and add this meter id to tests/test_c1_meters.sh ?

Thus "make test" should pass with this new telegram and we have a regression test for this meter. :-)

**Comment by trsqr** [comment]
Maybe you can help me out a bit here. I thought this was simple, but after adding:

```
$ git diff
diff --git a/simulations/simulation_c1.txt b/simulations/simulation_c1.txt
index ca365da..0ca682f 100644
--- a/simulations/simulation_c1.txt
+++ b/simulations/simulation_c1.txt
@@ -90,3 +90,7 @@ telegram=|5E462515112801000C1A7A370050252F2F|0BFD0F060101046D300CAB2202FD1700008
 # Test Techem radio convert + Wehrle water meter combo.
 telegram=|494468509494949495377286868686A85CFE07A90030052F2F|0413100000000F52FCF6A52A90A8D83CA8F7FEAE86990502323D0C70EFF49833C7C1696F75BCABC1E52E6305308D0F31FB|
 {"media":"water","meter":"weh_07","name":"Vatten","id":"86868686","total_m3":0.016,"timestamp":"1111-11-11T11:11:11Z"}
+
+# Test Zenner Minomess C1 water meter
+telegram=|6644496A1064035514377251345015496A0007EE0050052F2F|0C1359000000026CBE2B82046CA12B8C0413FFFFFFFF8D0493132CFBFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF02FD1700002F2F|
+{"media":"water","meter":"minomess","name":"Mino","id":"15503451","total_m3":0.059,"meter_date":"2021-11-30","target_m3":0,"target_date":"2021-11-01","status":"OK","timestamp":"1111-11-11T11:11:11Z"}
diff --git a/tests/test_c1_meters.sh b/tests/test_c1_meters.sh
index 1d0da61..5df91fc 100755
--- a/tests/test_c1_meters.sh
+++ b/tests/test_c1_meters.sh
@@ -25,6 +25,7 @@ $PROG --format=json simulations/simulation_c1.txt \
       myomnipower omnipower 32666857 NOKEY \
       Smokey ei6500 00012811 NOKEY \
       Vatten weh_07 86868686 NOKEY \
+      Mino minomess 55036410 NOKEY \
       > $TEST/test_output.txt 2> $TEST/test_stderr.txt
```

I do get error:

```
$ make test
Building minomess_1.5.0-16-g4005428 with local changes
OK: test internals
OK: Test C1 meters
OK json: Test T1 meters
OK fields: Test T1 meters
OK json: Test S1 meters
OK fields: Test S1 meters
OK: Test meter with unknown driver
OK json: Test naughty non-compliant apator162 meters
OK fields: Test naughty non-compliant apator162 meters
OK json: Test Izars meters
OK: Test listen to all izars
OK: Test aes encrypted telegrams
OK: Test that telegram really is encrypted
OK: Test that failed decryption warning only prints once.
OK: Test shell invocation
OK: Test shell in config file
OK: Test that normal meterfiles are written
OK: Test that meterfiles with name-id are written
OK: Test that meterfiles with id are written
OK: Test that meterfiles with timestamps are written
OK: Test that meterfiles with timestamps are written
22d21
< {"media":"water","meter":"minomess","name":"Mino","id":"15503451","total_m3":0.059,"meter_date":"2021-11-30","target_m3":0,"target_date":"2021-11-01","status":"OK","timestamp":"1111-11-11T11:11:11Z"}
ERROR: Test normal config files with C1 meters
```


Additionally, I have a question - what are the hasTotalWaterConsumption and hasTargetWaterConsumption used for?

**Comment by weetmuts** [comment]
Ah, there is a slight timing glitch when the second toggles in the middle of a test that checks timestamps, then it might fail. So please just run make test again, I intend to fix this....

The functions:
>hasTotalWaterConsumption and hasTargetWaterConsumption 
are historical artefacts from the start of wmbusmeters when I thought that I needed parent classes
and had to use hasSomething to check for stuff in the rendering. This was long before the addPrint functions.

It turns out that the meters are way more different than I expected, so having hasSomething functions to determine functionality will not work. You can expect the functions to go away in the future. addPrint is better.

**Comment by weetmuts** [comment]
Ah, sorrt I should have noticed "ERROR: Test normal config files with C1 meters"
this means that you have to add the file Mino into the directory tests/config1/etc/wmbusmeters.d
with the content:
name=Mino
type=minomess
id=55036410

**Comment by trsqr** [comment]
Thanks, that was the missing link indeed. Anything else that should be changed?

**Comment by weetmuts** [comment]
Good enough for now! Typically it is a bit tricky to figure out which of the two bytes are error byte a and b.
But if you have a chance to simulate a leak or burst, then we could see what bit get set.
This is of course tricky if the meter is already attached to your houes. ;-)

Many thanks for the driver!

**Comment by trsqr** [comment]
Great! Happy I could contribute and make wmbusmeters useful for myself as well. Really good job with the project - highly appreciated.

When it comes to the status bits Zenner was at least helpful enough to provide some specifications for me when I asked so I copied the information about them into the comments. Now there's a chance someone else can also implement the info codes...

**Pull request merged**
