### PR TITLE
Add support for Multical 403

### PR DESCRIPTION
**Pull request by eborned**
This pull adds support for the Multical403 in both heating and cooling configuration. I'm unable to add the tests for the heating configuration, because my meter is currently still at 0 usage due to the summer.

I'm not sure if the unit configuration is needed, but I've added the units that the meter uses for outputting its values.

### CODE REVIEW

**Comment by weetmuts** [comment]
Excellent work!

**Comment by dddevvv** [comment]
```
403     12345678        0 kWh   429.94 m3       0 m3/h  49.59 °C        32.13 °C                2020-12-15 19:50.15
403     12345678        0 kWh   429.94 m3       0 m3/h  49.46 °C        32.08 °C                2020-12-15 19:51.50
403     12345678        0 kWh   429.94 m3       0 m3/h  49.03 °C        31.99 °C                2020-12-15 19:53.24
403     12345678        0 kWh   429.94 m3       0 m3/h  48.61 °C        31.94 °C                2020-12-15 19:54.59
403     12345678        0 kWh   429.94 m3       0.076 m3/h      55.23 °C        24.04 °C                2020-12-15 19:56.33
403     12345678        0 kWh   429.95 m3       0 m3/h  60.26 °C        23.81 °C                2020-12-15 19:58.07
```
@eborned  did you manage to test this? Readings for my Multical 403 show zero for total energy usage.

**Comment by eborned** [comment]
> @eborned did you manage to test this? Readings for my Multical 403 show zero for total energy usage (it's not zero, although display shows [GJ]).

Yes, I have it running in production on three different locations (but with meters from the same provider). Maybe the configuration for your meter is different, resulting in some data not being processed correctly? Best way to debug this is by receiving a full telegram which we can decode.

The meter reports usage in kWh, which can be multiplied by 0.0036 to get the value in GJ.

**Comment by weetmuts** [comment]
Hi @dddevvv , can you post a telegram=|...| here, or email it to me? Then I can take alook
You run with --logtelegrams or --debug to get these lines.

wmbusmeters standardizes values to kwh, but add --addconversions=GJ to also have the gj
value calculated for you and added to the json struct.

**Comment by weetmuts** [comment]
I have seen in some meters that they can send either kwh or GJ. It is a configuration setting for the meter.
So ironically, in @eborned  meter, it sends GJ which is standardized to kwh, however the 403 driver
looks explicitly for gj data.

But your meter sends kwh directly, and the current code looks for gj, which it cannot find so the result becomes zero.

Fix is simple, make the findKey able to lookup energy (as either kwh or gj).
But I need a telegram from you @dddevvv  to verify this theory.

**Comment by dddevvv** [comment]
Thank you for your responses. Below is de --debug output 

```meter) 403: for me? 12345678
(meter) 403: yes for me
(meter) 403 multical403 handling telegram from 12345678
(meter) 403 12345678 "42442D2C34232571340C8D20F9845B8021835F5953EF2D8BC75D243F7F36614B0C43F69C21757996EC8D251259E0DA9CD402841BD090972A9D00345656DC074BDF697F"
(wmbus) parseDLL @0 67
(telegram) DLL L=42 C=44 (from meter SND_NR) M=2c2d (KAM) A=12345678 VER=34 TYPE=0c (Heat volume at inlet meter) (driver multical403) DEV=im871a[00102617] RSSI=-73
(wmbus) parseELL @10 57
(ELL) decrypting "835F5953EF2D8BC75D243F7F36614B0C43F69C21757996EC8D251259E0DA9CD402841BD090972A9D00345656DC074BDF697F"
(ELL) IV 2D2C34232571340C20845B8021000000
(ELL) block 0 block_size 16 offset 0
(ELL) decrypted "F14478040FFA18000004FF07F1730000"
(ELL) block 1 block_size 16 offset 16
(ELL) decrypted "04FF08D736000004140CA80000043B00"
(ELL) block 2 block_size 16 offset 32
(ELL) decrypted "00000002598014025D7F0C04FF220000"
(ELL) block 3 block_size 2 offset 48
(ELL) decrypted "0000"
(ELL) decrypted "F14478040FFA18000004FF07F173000004FF08D736000004140CA80000043B0000000002598014025D7F0C04FF2200000000"
(telegram) ELL CI=8d CC=20 (slow_resp sync) ACC=f9 SN=845b8021 (AES_CTR session=4 time=1574328) CRC=f144
(wmbus) parseAFL @19 48
(wmbus) parseTPL @19 48
(dvparser) found new format "040F04FF0704FF080414043B0259025D04FF22" with hash 787b, remembering!
(telegram) TPL CI=78
telegram=|42442D2C34232571340C8D20F9845B8021F14478|040FFA18000004FF07F173000004FF08D736000004140CA80000043B0000000002598014025D7F0C04FF2200000000|+357
(multical403) 00: 42 length (66 bytes)
(multical403) 01: 44 dll-c (from meter SND_NR)
(multical403) 02: 2d2c dll-mfct (KAM)
(multical403) 04: 34232571 dll-id (12345678)
(multical403) 08: 34 dll-version
(multical403) 09: 0c dll-type (Heat volume at inlet meter)
(multical403) 0a: 8d ell-ci-field (ELL: Extended Link Layer II (8 Byte))
(multical403) 0b: 20 ell-cc (slow_resp sync)
(multical403) 0c: f9 ell-acc
(multical403) 0d: 845b8021 sn (AES_CTR)
(multical403) 11: f144 payload crc (calculated f144 OK)
(multical403) 13: 78 tpl-ci-field (EN 13757-3 Application Layer (no tplh))
(multical403) 14: 04 dif (32 Bit Integer/Binary Instantaneous value)
(multical403) 15: 0F vif (Energy 10⁷ J)
(multical403) 16: FA180000
(multical403) 1a: 04 dif (32 Bit Integer/Binary Instantaneous value)
(multical403) 1b: FF vif (Vendor extension)
(multical403) 1c: 07 vife (?)
(multical403) 1d: F1730000
(multical403) 21: 04 dif (32 Bit Integer/Binary Instantaneous value)
(multical403) 22: FF vif (Vendor extension)
(multical403) 23: 08 vife (?)
(multical403) 24: D7360000
(multical403) 28: 04 dif (32 Bit Integer/Binary Instantaneous value)
(multical403) 29: 14 vif (Volume 10⁻² m³)
(multical403) 2a: * 0CA80000 total volume (430.200000 m3)
(multical403) 2e: 04 dif (32 Bit Integer/Binary Instantaneous value)
(multical403) 2f: 3B vif (Volume flow l/h)
(multical403) 30: * 00000000 volume flow (0.000000 m3/h)
(multical403) 34: 02 dif (16 Bit Integer/Binary Instantaneous value)
(multical403) 35: 59 vif (Flow temperature 10⁻² °C)
(multical403) 36: * 8014 T1 flow temperature (52.480000 °C)
(multical403) 38: 02 dif (16 Bit Integer/Binary Instantaneous value)
(multical403) 39: 5D vif (Return temperature 10⁻² °C)
(multical403) 3a: * 7F0C T2 flow temperature (31.990000 °C)
(multical403) 3c: 04 dif (32 Bit Integer/Binary Instantaneous value)
(multical403) 3d: FF vif (Vendor extension)
(multical403) 3e: 22 vife (per hour)
(multical403) 3f: * 00000000 info codes ()
```

**Comment by dddevvv** [comment]
Hi @weetmuts, maybe some additional information. Using the display/menu on the meter I understand it's configured to use datagram type "30-11-103".

image

**Comment by dddevvv** [comment]
I'm doing some investigation of my own, without any protocol knowledge. Seems my meter _does_ send out the value in GJ:

(multical403) 14: 04 dif (32 Bit Integer/Binary Instantaneous value)
(multical403) 15: 0F vif (Energy 10⁷ J)
(multical403) 16: FA180000

0xFA180000 endian swap (my guess) -> 0x18FF = 6394 = 63.94GJ = my current meter value on display.

Is the value at an unknown location in the datagram?

**Comment by eborned** [comment]
> edit: resolved by this patch to recognize the (previously unrecognized) 0xF VIF byte. Although I'm pretty sure it's not the right way.

Sounds very plausible to me. As my meter did not return the value, I did not add it to the mapping.

@weetmuts is there some way to map the telegram bytes to the registers from the documentation? To see if we missed some other possible values?

**Pull request merged**
