### PR TITLE
Improve the IZAR meter

### PR DESCRIPTION
**Pull request by ZeWaren**
I managed to fully decode the PRIOS protocol, used by IZAR meters.

This MR adds:
- The remaining battery life, in years.
- The date the second measurement was made (usually the last bill date).

### CODE REVIEW

**Comment by ZeWaren** [comment]
I also can provide the different alarms reported by the meter.

My implementation has them: https://github.com/ZeWaren/izar-prios-smart-meter-collector/blob/20bcd21d548c20bed90852b849944ea42da2c748/ST-STEVAL-FKI868V1/Src/PRIOS.c#L119

Is this something I can add to wmbusmeters? If yes, please tell me where I should put them. I didn't see other meters with alarm in the project.

**Comment by weetmuts** [comment]
Very nice! The multical21 has alarms they are simply part of a status field, like this:
"current_status":"DRY","time_dry":"22-31 days"

So perhaps something like this?

"current_status":"LEAK BLOCK BACKFLOW", "previous_status":"LEAK FRAUD"

**Comment by ZeWaren** [comment]
Done!
I've added the current alarms and the previous alarms to comma separated strings.

**Comment by weetmuts** [comment]
Thanks!

**Pull request merged**
