### PR TITLE
install.sh and uninstall.sh updates

### PR DESCRIPTION
**Pull request by BIBOLV**
Please check following editions
In install.sh:
updated help text
added check of passed arguments
add --no-udev-rule argument
added check of nologin shell and fallback to /bin/false if none found 
changed useradd cmd to work on different distros

In uninstall.sh:
added missing removal of files/dirs

### CODE REVIEW

**Comment by majekw** [comment]
I agree that install/uninstall scripts are a mess :-)
But blindly removing config and all logs is a bad idea.
During installation config should be put in file with extension like `default` (or dist, etc).
During removal script should only remove default config and remove directories **if empty**.
Another story is a great number of errors pointed by shellcheck in these scripts :-(

**Comment by BIBOLV** [comment]
Agree about existing uninstall.sh, correctly would be to rename it to purge.sh as that`s what it does.
Maybe also better would be to add uninstall part to install script itself? It would make install script bigger, but everything would be in one place.

**Comment by weetmuts** [comment]
Thank you very much @BIBOLV for the fixes to the install and uninstall scripts!
I can merge the pull request right away if you like.

Majekw, as for uninstall, my intent is to mimic debian uninstall of packages, I just have not
had time to do it yet. So that a simple uninstall.sh only removes the binaries.
But an "uninstall.sh --purge" to get rid of the config files and logs.

Or as you say Bibo, put them both in install. But I think it is slightly easier to have to scripts for this.
The scripts are meant to be called from the Makefile or from within the future debian package installer.

**Comment by weetmuts** [comment]
I just merged it because the --system fix to adduser etc was necessary anyway.
Lets work on a new pull request that improves the uninstall/install features!

**Comment by BIBOLV** [comment]
NP @weetmuts 
Could you please explain in few words your idea about uninstall.sh - I haven`t built any .deb packages, just .rpm`s ;)

**Pull request merged**
